/**
 * The cache that makes the AI feature affordable. The supplied token permits
 * 100 calls for its whole lifetime, so without a cache ten members opening the
 * same summary spends ten of them.
 *
 * The cache key is the compound unique index below:
 * (book, kind, length, language, promptVersion). Bumping AI_PROMPT_VERSION
 * invalidates everything generated by an older prompt without a migration.
 *
 * `isMock` marks content produced offline by the mock provider — never
 * presented as genuine model output.
 */

import mongoose from 'mongoose';
import {
  AI_SUMMARY_KIND,
  AI_SUMMARY_KIND_VALUES,
  AI_SUMMARY_LENGTH,
  AI_SUMMARY_LENGTH_VALUES,
} from '../constants/enums.js';

const { Schema, model } = mongoose;

const aiSummarySchema = new Schema(
  {
    book: { type: Schema.Types.ObjectId, ref: 'Book', required: true, index: true },

    kind: {
      type: String,
      enum: AI_SUMMARY_KIND_VALUES,
      required: true,
      default: AI_SUMMARY_KIND.SUMMARY,
    },

    length: {
      type: String,
      enum: AI_SUMMARY_LENGTH_VALUES,
      default: AI_SUMMARY_LENGTH.MEDIUM,
    },

    language: { type: String, default: 'en', lowercase: true, maxlength: 10 },

    /** A string for prose kinds, an array for KEY_TAKEAWAYS. */
    content: { type: Schema.Types.Mixed, required: true },

    /* --- Q&A ------------------------------------------------------------ */

    /** The question asked. Only set when kind is QA. */
    question: { type: String, trim: true, maxlength: 500, default: null },

    /**
     * SHA-256 of the NORMALISED question. Normalising first is what makes the
     * cache hit: "What is the main theme?" and "what is the main theme" are
     * the same question and must not cost two calls.
     */
    questionHash: { type: String, default: null, index: true },

    /* --- Provenance ------------------------------------------------------- */

    model: { type: String, default: null },

    /**
     * Part of the cache key. Bump AI_PROMPT_VERSION to invalidate everything
     * generated by an older prompt, without writing a migration.
     */
    promptVersion: { type: String, required: true },

    /** Hash of the source material, so a rewritten description marks the summary stale. */
    inputHash: { type: String, default: null },

    /** Whether the source was extracted ebook text or just catalogue metadata. */
    sourceType: {
      type: String,
      enum: ['METADATA', 'FULL_TEXT', 'EXCERPT'],
      default: 'METADATA',
    },

    /** True when produced offline by the mock provider. Surfaced in every response. */
    isMock: { type: Boolean, default: false, index: true },

    promptTokens: { type: Number, default: 0 },
    completionTokens: { type: Number, default: 0 },

    generatedAt: { type: Date, default: Date.now },
    /** Null for automatic generation; set when staff explicitly regenerated. */
    generatedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },

    /** How often this cached entry has been served. Proves the cache's value. */
    hitCount: { type: Number, default: 0 },
    lastServedAt: { type: Date, default: null },
  },
  { timestamps: true, toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

/* Indexes */

/**
 * The cache key. Unique, so two members racing for the same summary cannot
 * produce two entries and spend a second API call. Q&A is excluded
 * (`questionHash: null`) and keyed separately below.
 */
aiSummarySchema.index(
  { book: 1, kind: 1, length: 1, language: 1, promptVersion: 1 },
  {
    unique: true,
    partialFilterExpression: { questionHash: null },
    name: 'ai_summary_cache_key',
  }
);

/** The Q&A cache: one answer per normalised question per book. */
aiSummarySchema.index(
  { book: 1, questionHash: 1, promptVersion: 1 },
  {
    unique: true,
    partialFilterExpression: { questionHash: { $type: 'string' } },
    name: 'ai_qa_cache_key',
  }
);

/** Finding mock entries worth regenerating once a real token exists. */
aiSummarySchema.index({ isMock: 1, generatedAt: -1 });

/* Statics */

/** Look up a cached summary. */
aiSummarySchema.statics.findCached = function findCached({
  book,
  kind,
  length,
  language,
  promptVersion,
}) {
  return this.findOne({ book, kind, length, language, promptVersion, questionHash: null });
};

/** Look up a cached answer to a question. */
aiSummarySchema.statics.findCachedAnswer = function findCachedAnswer({
  book,
  questionHash,
  promptVersion,
}) {
  return this.findOne({ book, questionHash, promptVersion });
};

/**
 * Record that a cached entry was served.
 *
 * Fire-and-forget from the caller's perspective — the statistic is worth
 * having (it is the evidence that caching is doing its job) but not worth
 * delaying a response for.
 */
aiSummarySchema.statics.recordHit = function recordHit(id) {
  return this.updateOne({ _id: id }, { $inc: { hitCount: 1 }, $set: { lastServedAt: new Date() } });
};

export const AiSummary = model('AiSummary', aiSummarySchema);

export default AiSummary;
